# Generated by Django 3.1.7 on 2021-04-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210420_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalGroceryImage',
        ),
    ]
