# Generated by Django 3.1.7 on 2021-04-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_localgroceryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
