# Generated by Django 3.1.7 on 2021-04-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210430_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campaign_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.campaign'),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.offer'),
        ),
    ]
