# Generated by Django 3.1.7 on 2021-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('seller_name', models.CharField(max_length=120)),
                ('seller_nid', models.CharField(max_length=120)),
                ('seller_email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('commision', models.IntegerField()),
                ('seller_phone', models.CharField(max_length=120)),
                ('seller_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
