# Generated by Django 3.1.7 on 2021-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='market_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
